spring:
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:web_crawler.sqlite
    tomcat:
      max-active: 20
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.SQLiteDialect
  messages:
    basename: i18n/messages
    encoding: UTF-8
server:
  port: 8085





